### ISSUE TITLE
Website not rendering correctly

### ISSUE THREAD

**Issue by philipturner** [dkhamsing/open-source-ios-apps#974] opened 2021-09-07 15:16 UTC
The website hosted by this GitHub repository duplicates its presentation of some iOS apps several times, each with a different number of GitHub stars. This doesn't appear to be desired behavior.

 Here are a few screenshots:

![IMG_1373](https://user-images.githubusercontent.com/71743241/132367673-d12380f9-c6ce-45a0-9788-92a590aa2f2d.PNG)
![IMG_1374](https://user-images.githubusercontent.com/71743241/132368100-75c6ecdf-4c19-4d34-9481-531d3d2e7864.jpg)
<img width="2130" alt="Open Source iOS Apps Screenshot" src="https://user-images.githubusercontent.com/71743241/132369305-4fcceb3b-3485-4f06-aa1c-75533dddd160.png">

**Comment by chmac** [comment] 2021-09-07 15:29
The context of this is in #917.

**Comment by chmac** [comment] 2021-09-07 15:31
Unfortunately it's hard to know why the cache is interfering, and I was unable to reproduce it on my netlify build. Plus I don't have access to the production netlify as it's on @dkhamsing's account. Maybe there's a way to exclude some folders from the netlify cache which would fix the issue. If somebody is open to investigating that, there might be a long term fix. I don't know if it's also possible to simply disable netlify caching, but then the builds might take longer, and the account may run out of minutes by the end of the month...

**Comment by dkhamsing** [comment] 2021-09-07 15:36
Should be fixed, for now - see #917

**Closed by dkhamsing** 2021-09-07 15:36 UTC
